/*
 * wv_internal.h — shared state handle for the LFE tab modules.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Each `tab_<name>.c` needs to read and write a handful of fields in
 * the shared `wv` state: its own row_row / preset / length fields, the
 * status line, the current sample index, etc. Exposing the whole
 * WaveformViewState struct keeps cross-file calls cheap at the cost of
 * making `wv` globally visible.
 *
 * This header is NOT a public interface. It is only included by
 * `waveform_view.c` and by the `tab_<name>.c` modules alongside it.
 * The Step-5 encapsulation pass will delete most of this file and move
 * per-tab fields into file-scoped structs inside each tab module.
 */

#ifndef WV_INTERNAL_H
#define WV_INTERNAL_H

#ifdef MAXTRACKER_LFE

#include <nds.h>
#include <stdbool.h>
#include <stdint.h>

#include "lfe.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Generator tabs. Order is the L/R tab-cycle order. The Test Tone tab
 * is a developer-only sanity check — gated on
 * MAXTRACKER_LFE_ENABLE_TESTTONE which is NOT set in normal builds. */
typedef enum {
#ifdef MAXTRACKER_LFE_ENABLE_TESTTONE
    WV_GEN_TEST_TONE,
#endif
    WV_GEN_DRUM,
    WV_GEN_SYNTH,
    WV_GEN_FM4,
    WV_GEN_BRAIDS,
    WV_GEN_DRAWN,
    WV_GEN_COUNT,
} wv_gen;

/* Default tab at open. Drum is the first always-present generator; it
 * moves up to index 0 when Test Tone is compiled out. */
#ifdef MAXTRACKER_LFE_ENABLE_TESTTONE
#  define WV_GEN_DEFAULT WV_GEN_TEST_TONE
#else
#  define WV_GEN_DEFAULT WV_GEN_DRUM
#endif

/* Drawn-canvas width; fixed single-cycle buffer length. */
#define WV_CANVAS_LEN 256

typedef struct {
    bool   active;
    int    sample_idx;
    wv_gen current_gen;
    int    vis_zoom;

    /* Sample length in ms. Shared across all generators that render
     * offline buffers (drum / synth / fm4 / braids) — every tab's
     * "Length (ms)" row reads/writes this single field so switching
     * tabs keeps the same duration. Seeded by waveform_view_open().
     * The sample-rate is fixed at 32 kHz today, so the generated byte
     * size is length_ms × 64. */
    int length_ms;

    /* Test Tone state encapsulated in tab_tone.c (Step 5). */

    /* Drawn canvas state encapsulated in tab_drawn.c (Step 5). */

    /* Drum state encapsulated in tab_drum.c (Step 5). */

    /* Synth state encapsulated in tab_synth.c (Step 5). */

    /* FM4 state encapsulated in tab_fm4.c (Step 5). */

    /* Braids state encapsulated in tab_braids.c (Step 5). */

    /* Lifecycle / status */
    bool draft_dirty;
    bool exit_pending;
    char status[48];
    int  status_timer;
} WaveformViewState;

extern WaveformViewState wv;

/*
 * Take ownership of a freshly-generated int16 PCM buffer and install it
 * as the current draft. Called by every tab's `<tab>_generate` at the
 * end of a successful render. loop_length>0+loop_type=1 for sustained
 * samples; loop_length=0+loop_type=0 for one-shots. `name_prefix` is
 * the leading word of the sample name ("Tone", "Drum", ...).
 */
void wv_write_draft_16(int16_t *pcm,
                       uint32_t length,
                       uint32_t rate,
                       uint32_t loop_length,
                       u8 loop_type,
                       const char *name_prefix);

/*
 * Format the shared length_ms alongside its resulting byte-size estimate
 * as a single string — "1000 (64K)" style. Writes into `buf` (up to
 * `n` bytes). Every tab's "Length (ms)" row format function calls this
 * so the size readout is consistent across generators. The rate is the
 * one the tab's generate() will use — presently 32 kHz for every tab,
 * but the parameter is explicit so future low-rate tabs don't mislead. */
void wv_format_length_with_size(char *buf, int n, int length_ms, uint32_t rate_hz);

#ifdef __cplusplus
}
#endif

#endif /* MAXTRACKER_LFE */

#endif /* WV_INTERNAL_H */
